server:
  port: 9002

spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        # nacos 服务器地址
        server-addr: 192.168.174.129:8848
        # nacos 服务器用户名
        username: nacos
        # nacos 服务器密码
        password: nacos
        # 命名空间
        namespace: public
